name: supermarket
channels:
  - pytorch-lts
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - cudatoolkit==11.1.74
  - matplotlib
  - numpy
  - pip
  - python==3.8
  - pytorch==1.8.2
  - tensorboard
  - torchvision==0.9.2
  - simplejson
  - scikit-learn
  - psutil
  - tqdm
  - timm
  - pandas
  - Pillow
  - pytorch-lightning
  - ipywidgets
  - pip:
    - opencv-python
    - onnxruntime-gpu
    - lightning-flash[image]
    - icevision[all]==0.8.1
    - https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.8/detectron2-0.6%2Bcu111-cp38-cp38-linux_x86_64.whl
